### ISSUE TITLE
点击选择图片按钮闪退

### ISSUE THREAD

**Issue by lovewmf** [fanqieVip/AndroidOcrLibs#5]

**Comment by fanqieVip** [comment]
那个忽略吧，反正用不上的

**Comment by lovewmf** [comment]
能不能类似这样bundle.putInt("show",false);把那个选择图片的按钮隐藏掉，或者直接在界面取消

**Comment by lovewmf** [comment]
或者介不介意我直接修改

**Comment by fanqieVip** [comment]
我的源码里面有个身份证扫描的activity，你直接用那个也可以的

**Comment by deboLing** [comment]
> 我的源码里面有个身份证扫描的activity，你直接用那个也可以的

使用这个activity去识别身份证，反而识别不出来   识别率不高  不知为何

**Comment by liliangzdh** [comment]
修改 aar 的文件。把里面的  布局 的 selectImage 添加个 android:visibility="gone" 完事。自己修改，挺快的
